buildscript {
	ext {
		springBootVersion = '3.5.3'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.10'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'mercadolibre.com'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

apply from: './main.gradle'
