spring.jackson.default-property-inclusion=non_null
#logging.level.org.springframework.web=DEBUG
#logging.level.mercadolibre.com.reactive=DEBUG

#=== data base ===  #
json.file.path=products.json
maximum.retries=3
retry.cycle=1

#=== data base ===  #
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
queue.name=update-stock-queue
exchange.name=update-stock-exchange
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10