name: Continuos Integration
on: # Cuando se activara la integrqación continua
  pull_request: # con que medio se activara (pull_request, push)
    branches: # las ramas donde se acrtiva
      - develop
      - main
      - release
      - master

jobs:
  build:
    runs-on: ubuntu-latest # donde vamos correr el CI
    steps:
      - uses: actions/checkout@v5 #se usa en GitHub Actions para clonar el repositorio en el entorno del workflow.
        name: sistema-distribución

      - name: Instalar Java
        uses: actions/setup-java@v5
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Instalar gradle
        uses: gradle/gradle-build-action@v3

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x ./gradlew

      - name: Compilando
        run: ./gradlew build